controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    omni_wheel_controller:
      type: omni_wheel_controller/OmniWheelController

    wheels_pid_controller:
      type: pid_controller/PidController

    gimbal_controller:
      type: gimbal_controller/GimbalController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

omni_wheel_controller:
  ros__parameters:
    omni_wheel_joints:
      - wheels_pid_controller/front_wheel_joint
      - wheels_pid_controller/left_wheel_joint
      - wheels_pid_controller/back_wheel_joint
      - wheels_pid_controller/right_wheel_joint

    omni_wheel_angles: [0.0, 90.0, 180.0, -90.0]

    omni_wheel_distance: 0.196

    omni_wheel_radius: 0.05

wheels_pid_controller:
  ros__parameters:
    dof_names:
      - front_wheel_joint
      - left_wheel_joint
      - back_wheel_joint
      - right_wheel_joint

    command_interface: effort

    reference_and_state_interfaces: ["velocity"]

    gains:
      front_wheel_joint: {p: 1.0, i: 0.0, d: 0.0}
      left_wheel_joint: {p: 1.0, i: 0.0, d: 0.0}
      back_wheel_joint: {p: 1.0, i: 0.0, d: 0.0}
      right_wheel_joint: {p: 1.0, i: 0.0, d: 0.0}

gimbal_controller:
  ros__parameters:
    gimbal_joints:
      - yaw_gimbal_joint
      - pitch_gimbal_joint

    gimbal_roles:
      - yaw
      - pitch

    imu_topic: /gimbal_imu

    gains:
      yaw_gimbal_joint: {p: 15.0, i: 0.0, d: 0.4}
      pitch_gimbal_joint: {p: 10.0, i: 0.0, d: 0.5}

