/**:
  ros__parameters:

    chassis:
      mode: 1
    # 0->enable all, 1->only chassis movement, 2->only absolute movement, 3->only natural movement

    motor:
      count:  4
      rids:   ["F", "L", "B", "R"]
      hids:   [1, 2, 3, 4]
      brands: [0, 0, 0, 0] # 0->dji, 1->dm
      types:  [0, 0, 0, 0]
    # for dji: 0->3508, 1->6020, 2->2006
    # for dm: 0->vel, 1->mit, 2->pos_vel

      p2v:
        kps: [0.1,     0.1,     0.1,     0.1]
        kis: [0.001,   0.001,   0.001,   0.001]
        kds: [0.1,     0.1,     0.1,     0.1]

      v2c:
        kps: [0.01,  0.01,  0.01,  0.01]
        kis: [0.00002, 0.00002, 0.00002, 0.00002]
        kds: [0.2,     0.2,     0.2,     0.2]