/**:
  ros__parameters:

    # for node `dji_controller` and `motor_feedback`
    motor:
      count: 1
      rids: ["YAW"]
      hids: [5]
      brands: [0]  # 0->dji, 1->dm
      types: [1]  # for dji: 0->3508, 1->6020, 2->2006; for dm: 0->vel, 1->mit, 2->pos_vel

      # for node `dji_controller`
      p2v:
        kps: [0.8]
        kis: [0.001]
        kds: [1.0]
      v2c:
        kps: [2.7]
        kis: [0.6]
        kds: [2.0]