/**:
  ros__parameters:

    motor:
      count: 1
      rids: ["J1", "J2"]
      hids: [2, 1]
      ports: ["CAN0", "CAN0"]
      brands: ["DJI", "DJI"]
      types: ["3508", "3508"]

      p2v:
        kps: [2.5E+1, 2.5E+1]
        kis: [1.5E+1, 1.5E+1]
        kds: [1.0E+4, 1.0E+4]
      v2c:
        kps: [4.2E-2, 4.2E-2]
        kis: [3.0E-4, 3.0E-4]
        kds: [0.0E+3, 0.0E+3]
      
      cali: [1, 0]