/**:
  ros__parameters:

    # for node `dji_controller` and `motor_feedback`
    motor:
      count: 1
      rids: ["J7"]
      hids: [5]
      ports: ["CAN0"]
      brands: ["DJI"]  # 0->dji, 1->dm
      types: ["2006"]

      # for node `dji_controller`
      p2v:
        kps: [1.0E+2]
        kis: [0.0E+0]
        kds: [0.0E+0]
      v2c:
        kps: [5.0E-2]
        kis: [1.5E-1]
        kds: [1.0E+1]