/**:
  ros__parameters:

    # for node `dji_controller` and `motor_feedback`
    motor:
      count: 4
      rids: ["J4", "J5", "J6", "J7",]
      hids: [6, 7, 8, 5,]
      brands: [0, 0, 0, 0,]  # 0->dji, 1->dm
      types: [0, 0, 0, 2,]  # for dji: 0->3508, 1->6020, 2->2006; for dm: 0->vel, 1->mit, 2->pos_vel

      # for node `dji_controller`
      p2v:
        kps: [0.8, 0.8, 0.8, 0.8,]
        kis: [0.001, 0.001, 0.001, 0.001,]
        kds: [1.0, 1.0, 1.0, 1.0,]
      v2c:
        kps: [0.002, 0.002, 0.002, 0.002,]
        kis: [0.000001, 0.000001, 0.000001, 0.000001,]
        kds: [0.0, 0.0, 0.0, 0.0,]