/motor_tester:
  ros__parameters:
    # motor_rid: "t1"
    # goal_type: "pos"
    # goal_upper: 1.7
    # goal_lower: -3.4
    # goal_init: -1.0
    # sensitivity: 1.0 # per second
    # deadzone: 0.2

    motor_rid: "t0"
    goal_type: "pos"
    goal_upper: 0.0
    goal_lower: -6.0
    goal_init: 0.0
    sensitivity: 2.0 # per second
    deadzone: 0.2