/**:
  ros__parameters:

    chassis:
      mode: 1
      # 0->enable all, 1->only chassis movement, 2->only absolute movement, 3->only natural movement

    motor:
      count: 8
      rids:   [LF_V, RF_V, RB_V, LB_V, LF_D, RF_D, RB_D, LB_D]
      hids:   [1, 2, 3, 4, 1, 2, 3, 4]
      brands: [0, 0, 0, 0, 0, 0, 0, 0] # 0->dji, 1->dm
      types:  [0, 0, 0, 0, 1, 1, 1, 1]
      # for dji: 0->3508, 1->6020, 2->2006
      # for dm: 0->vel, 1->mit, 2->pos_vel

      p2v:
        kps: [0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.2, 0.2]
        kis: [0.0, 0.0, 0.0, 0.0, 0.001, 0.001, 0.001, 0.001]
        kds: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

      v2c:
        kps: [0.0025, 0.0025, 0.0025, 0.0025, 0.4, 0.8, 0.8, 0.8]
        kis: [0.0000, 0.0000, 0.0000, 0.0000, 0.0005, 0.001, 0.001, 0.001]
        kds: [0.03, 0.03, 0.03, 0.03, 0.0, 0.0, 0.0, 0.0]