/**:
  ros__parameters:

    chassis:
      move_mode: "chassis"

    motor:
      count:   8
      rids:    ["LF_V",    "RF_V",    "RB_V",    "LB_V",    "LF_D",    "RF_D",    "RB_D",    "LB_D"]
      hids:    [1,         2,         3,         4,         2,         3,         4,         1]
      brands:  ["DJI",     "DJI",     "DJI",     "DJI",     "DJI",     "DJI",     "DJI",     "DJI"]
      types:   ["3508",    "3508",    "3508",    "3508",    "6020",    "6020",    "6020",    "6020"]

      p2v:
        kps:   [0.0,       0.0,       0.0,       0.0,       1.0E+1,    1.0E+1,    1.0E+1,    1.0E+1]
        kis:   [0.0,       0.0,       0.0,       0.0,       4.5E+0,    7.5E+0,    4.5E-1,    4.5E-1]
        kds:   [0.0,       0.0,       0.0,       0.0,       1.0E+4,    1.0E+4,    1.0E+4,    1.0E+4]

      v2c:
        kps:   [1.2E-2,    1.2E-2,    1.2E-2,    1.2E-2,    1.0E+0,    1.5E+0,    1.0E+0,    2.5E+0]
        kis:   [1.0E-4,    1.0E-4,    1.0E-4,    1.0E-4,    3.5E+1,    6.5E+1,    3.5E+0,    3.5E+0]
        kds:   [0.0E+3,    0.0E+3,    0.0E+3,    0.0E+3,    0.0E+0,    0.0E+0,    0.0E+0,    1.0E+0]