/**:
  /ros_parameters:

    motor_count: 8
    motor_names: ["LF0", "RF0", "LB0", "RB0", "LF1", "RF1", "LB1", "RB1"] # only used for labeling, does not appear in code
    # 0->direction, 1->speed
    motor_brands: [0, 0, 0, 0, 0, 0, 0, 0] # 0->dji, 1->dm
    motor_modes: [1, 1, 1, 1, 0, 0, 0, 0] # 0->vel, 1->pos/mit
    motor_types: [1, 1, 1, 1, 0, 0, 0, 0]
    # for dji: 0->3508, 1->6020, 2->2006
    # for dm: 0->4310