controller_manager:
  ros__parameters:
    update_rate: 250 # Hz

    omni_chassis_controller:
      type: meta_chassis_controller/OmniChassisController

    wheels_pid_controller:
      type: pid_controller/PidController

    # gimbal_controller:
    #   type: gimbal_controller/GimbalController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

omni_chassis_controller:
  ros__parameters:
    omni_wheel_joints:
      - wheels_pid_controller/front_wheel_joint
      - wheels_pid_controller/left_wheel_joint
      - wheels_pid_controller/back_wheel_joint
      - wheels_pid_controller/right_wheel_joint

    omni_wheel_angles: [0.0, 90.0, 180.0, -90.0]

    omni_wheel_distance: 0.196

    omni_wheel_radius: 0.05

    control_mode: 0

    yaw_gimbal_joint: yaw_gimbal_joint

    follow_pid_gains: { p: 2.0, i: 0.0, d: 0.0 }

wheels_pid_controller:
  ros__parameters:
    dof_names:
      - front_wheel_joint
      - left_wheel_joint
      - back_wheel_joint
      - right_wheel_joint

    command_interface: effort

    reference_and_state_interfaces: ["velocity"]

    gains:
      front_wheel_joint:
        {
          p: 2.0e-3,
          i: 1.0e-5,
          d: 0.0,
          i_clamp_max: 1.0,
          i_clamp_min: -1.0,
          antiwindup: true,
        }
      left_wheel_joint:
        {
          p: 2.0e-3,
          i: 1.0e-5,
          d: 0.0,
          i_clamp_max: 1.0,
          i_clamp_min: -1.0,
          antiwindup: true,
        }
      back_wheel_joint:
        {
          p: 2.0e-3,
          i: 1.0e-5,
          d: 0.0,
          i_clamp_max: 1.0,
          i_clamp_min: -1.0,
          antiwindup: true,
        }
      right_wheel_joint:
        {
          p: 2.0e-3,
          i: 1.0e-5,
          d: 0.0,
          i_clamp_max: 1.0,
          i_clamp_min: -1.0,
          antiwindup: true,
        }
# gimbal_controller:
#   ros__parameters:
#     gimbal_joints:
#       - yaw_gimbal_joint
#       - pitch_gimbal_joint

#     gimbal_roles:
#       - yaw
#       - pitch

#     imu_topic: /gimbal_imu

#     gains:
#       yaw_gimbal_joint_pos2vel: { p: 13.0, i: 0.0, d: 0.4 }
#       pitch_gimbal_joint_pos2vel: { p: 10.0, i: 0.0, d: 0.5 }
#       yaw_gimbal_joint_vel2eff: { p: 0.26, i: 0.2, d: 0.00003 }
#       pitch_gimbal_joint_vel2eff: { p: 0.26, i: 0.1, d: 0.0001 }
