/motor_controller:
  /ros__parameters:

    # ids are in the order of motor_names, "LF" is 0
    motor_count: 8
    motor_names: ["LF", "RF", "LH", "RH", "SHOOTER", "LOADER", "YAW", "PITCH"] # only used for labeling, does not appear in code
    motor_brands: [0, 0, 0, 0, 0, 0, 1, 1] # 0: dji, 1: dm
    motor_modes: [0, 0, 0, 0, 0, 1, 1, 1] # 0: vel, 1: pos/mit
    
    motor_types: [0, 0, 0, 0, 0, 1, 0, 0]
    # for dji: 0: 3508, 1: 6020, 2: 2006
    # for dm: 0: 4310

