/**:
  ros__parameters:

    chassis:
      mode: 1
      # 0->enable all, 1->only chassis movement, 2->only absolute movement, 3->only natural movement
      yaw_ratio: 100.0 # MY_TODO: to be tuned

    motor:
      count:  3
      rids:   ["FRIC_U", "FRIC_D", "FEED_L"]
      hids:   [5, 6, 7]
      brands: [0, 0, 0] # 0->dji, 1->dm
      types:  [0, 0, 0]
      # for dji: 0->3508, 1->6020, 2->2006
      # for dm: 0->vel, 1->mit, 2->pos_vel

      p2v:
        kps: [0.0, 0.0, 0.0]
        kis: [0.0, 0.0, 0.0]
        kds: [0.0, 0.0, 0.0]

      v2c:
        kps: [0.004, 0.004, 0.004]
        kis: [0.00001, 0.00001, 0.0001]
        kds: [0.1, 0.1, 0.00]