/**:
  ros__parameters:

    motor:
      count:  1
      rids:   ["test"]
      hids:   [0x10]
      brands: [2] # 0->dji, 1->dm, 2->unitree
      types:  [0]
    # for dji: 0->3508, 1->6020, 2->2006
    # for dm: 0->vel, 1->mit, 2->pos_vel

    p2v:
      kps: [0.006]
      kis: [0.0]
      kds: [0.002]

    v2c:
      kps: [0.0]
      kis: [0.0]
      kds: [0.0]