/**:
  ros__parameters:

    motor:
      count:  2
      rids:   ["t0", "t1"]
      hids:   [0x00, 0x01]
      brands: ["UT", "UT"]
      types:  ["", ""]
      ports:  ["USB0", "USB0"]

      p2v:
        kps: [0.2, 0.1]
        kis: [0.0, 0.0]
        kds: [0.05, 0.05]

      v2c:
        kps: [0.0, 0.0]
        kis: [0.0, 0.0]
        kds: [0.0, 0.0]