/**:
  ros__parameters:

    north_offset: 0.0 # rad, north against the desired front
    trans_vel: 3.0 # m/s
    rot_vel: 6.0 # rad/s
    
    chassis:
      wheel_radius: 0.076 # m
      deceleration_ratio: 20.0
      chassis_radius: 0.255 # m

    motor:
      count:  8
      rids:   ["LF_V", "RF_V", "RB_V", "LB_V", "LF_D", "RF_D", "RB_D", "LB_D"]
      hids:   [1, 2, 3, 4, 8, 9, 10, 11, ]
      brands: [0, 0, 0, 0, 0, 0, 0, 0, ] # 0->dji, 1->dm
      types:  [0, 0, 0, 0, 1, 1, 1, 1, ]
      # for dji: 0->3508, 1->6020, 2->2006
      # for dm: 0->vel, 1->mit, 2->pos_vel
      offsets: [0.0,  0.0,  0.0,  0.0,  1.0,  1.0,  1.0,  1.0, ]
      p2v:
        kps: [0.0,   0.0,   0.0,   0.0,   1.0,   1.0,   1.0,   1.0, ]
        kis: [0.0,   0.0,   0.0,   0.0,   1.0,   1.0,   1.0,   1.0, ]
        kds: [0.0,   0.0,   0.0,   0.0,   1.0,   1.0,   1.0,   1.0, ]
      v2c:
        kps: [0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, ]
        kis: [0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002, ]
        kds: [0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100, ]