/**:
  ros__parameters:

    control:
      end_linear_vel: 0.0 # m/s
      end_angular_vel: 0.0 # rad/s

    motor:
      count:   7
      rids:    ["J1",      "J2",      "J3",      "J4",      "J5",      "J6",      "J7"]
      hids:    [4,         0,         1,         2,         3,         1,         5]
      ports:   ["CAN0",    "USB0",    "USB0",    "CAN0",    "CAN0",    "CAN0",    "CAN0"]
      brands:  ["DJI",     "UT",      "UT",      "DJI",     "DJI",     "DJI",     "DJI"]
      types:   ["3508",    "",        "",        "3508",    "3508",    "3508",    "2006"]

      p2v:
        kps:   [2.5E+1,    0.4E+0,    0.1E+0,    1.8E+1,    3.0E+1,    2.8E+1,    1.0E+2]
        kis:   [1.5E+1,    0.0E+0,    0.0E+0,    1.0E+0,    2.0E+0,    2.0E+0,    0.0E+0]
        kds:   [1.0E+4,    0.0E+0,    0.0E+0,    1.0E+4,    1.1E+4,    1.0E+3,    0.0E+0]

      v2c:
        kps:   [1.5E-1,    0.0E-2,    0.0E-2,    8.0E-2,    1.0E-1,    1.0E-1,    5.0E-2]
        kis:   [5.0E-3,    0.0E-4,    0.0E-4,    1.0E-4,    1.0E-2,    1.0E-2,    1.5E-1]
        kds:   [0.0E+3,    0.0E+3,    0.0E+3,    0.0E+3,    0.0E+3,    0.0E+3,    1.0E+1]

      cali:    [0,         1,         -1,        1,         1,         1,         -1]