/**:
  ros__parameters:

    chassis:
      mode: 1
      # 0->enable all, 1->only chassis movement, 2->only absolute movement, 3->only natural movement
      yaw_ratio: 100.0 # MY_TODO: to be tuned

    motor:
      count:  10
      ids:    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      brands: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] # 0->dji, 1->dm
      types:  [0, 0, 0, 0, 0, 0, 2, 2, 1, 1]
      # for dji: 0->3508, 1->6020, 2->2006
      # for dm: 0->vel, 1->mit, 2->pos_vel

      p2v:
        kps: [0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     1.0]
        kis: [0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     1.0]
        kds: [0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     1.0]

      v2c:
        kps: [0.004,   0.004,   0.004,   0.004,   0.004,   0.004,   0.004]
        kis: [0.00003, 0.00003, 0.00003, 0.00003, 0.00003, 0.00003, 0.00003]
        kds: [0.1,     0.1,     0.1,     0.1,     0.1,     0.1,     0.1]