/**:
  ros__parameters:

    north_offset: 0.0 # rad, north against the desired front
    auto_rotate: 4.0 # rad/s, of the chassis
    comp_ratio: 0.9
    move_mode: "natural"
    referee_port: "ttyUSB1"
    dbus_port: "dbus_serial"

    control:
      trans_vel: 2.5 # m/s
      rot_vel: 3.0 # rad/s
      stick_sens: 5.00 # rad/s
      mouse_sens: 10.0
      deadzone: 0.15 # percentage
    
    chassis:
      wheel_radius: 0.076 # 0.076 # m
      deceleration_ratio: 20.0
      chassis_radius: 0.255 # m
      yaw_offset: -0.245 # rad, yaw's zero against the chassis front

    gimbal:
      fric_vel_u: -800.0 #-800.0
      fric_vel_d: 800.0 #+800.0
      fric_ratio: 1.0
      feed_vel_l: 5.0
      feed_vel_r: -8.0 #15.0
      feed_ratio: 36.0
      drawback_delay: 500 # ms
      jammed_threshold: 1.0 # rad/s
      search_vel: -2.0
      pitch_freq: 2.0
      pitch_amp: 0.0
      aim_yaw_offset: 0.0872664626
      aim_pitch_offset: 0.080

    motor:
      count:  10
      rids:   ["F",       "L",       "B",       "R",       "FRIC_U",  "FRIC_D",  "FEED_L",  "FEED_R",  "YAW",     "PITCH"]
      hids:   [1,         4,         2,         3,         5,         6,         8,         7,         5,         6]
      ports:  ["CAN0",    "CAN0",    "CAN0",    "CAN0",    "CAN0",    "CAN0",    "CAN0",    "CAN0",    "CAN0",    "CAN0"]
      brands: ["DJI",     "DJI",     "DJI",     "DJI",     "DJI",     "DJI",     "DJI",     "DJI",     "DJI",     "DJI"]
      types:  ["3508",    "3508",    "3508",    "3508",    "3508",    "3508",    "2006",    "2006",    "6020",    "6020"]

      p2v:
        kps:  [0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       7.0E+0,    3.0E+1]
        kis:  [0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0E-1,    0.0E+0]
        kds:  [0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0E-2,    5.0E-2]
      v2t:
        kps:  [2.0E-2,    2.0E-2,    2.0E-2,    2.0E-2,    1.0E-2,    1.0E-2,    5.0E-2,    5.0E-2,    1.0E+1,    2.0E+0]
        kis:  [1.0E-4,    1.0E-4,    1.0E-4,    1.0E-4,    1.2E-2,    1.6E-2,    2.5E-1,    2.5E-1,    5.0E+0,    4.0E-1]
        kds:  [0.0E+3,    0.0E+3,    0.0E+3,    0.0E+3,    0.0E+3,    0.0E+3,    1.0E+2,    1.0E+2,    0.0E+0,    0.0E+0]

      cali:   [0,         0,         0,         0,         0,         0,         0,         0,         0,         0]