/**:
  ros__parameters:

    chassis:
      mode: 1
      # 0->enable all, 1->only chassis movement, 2->only absolute movement, 3->only natural movement

    gimbal:
      yaw_ratio: 100.0 # MY_TODO: to be tuned
      fric_vel_u: 500.0
      fric_vel_d: -500.0
      feed_vel_l: 300.0
      feed_vel_r: 300.0

    motor:
      count:  10
      rids:   ["F", "L", "B", "R", "FRIC_U", "FRIC_D", "FEED_L", "FEED_R", "YAW", "PITCH"]
      hids:   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      brands: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] # 0->dji, 1->dm
      types:  [0, 0, 0, 0, 0, 0, 2, 2, 1, 1]
      # for dji: 0->3508, 1->6020, 2->2006
      # for dm: 0->vel, 1->mit, 2->pos_vel

      p2v:
        kps: [0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     1.0]
        kis: [0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     1.0]
        kds: [0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     1.0]

      v2c:
        kps: [0.004,   0.004,   0.004,   0.004,   0.004,   0.004,   0.004]
        kis: [0.00003, 0.00003, 0.00003, 0.00003, 0.00003, 0.00003, 0.00003]
        kds: [0.1,     0.1,     0.1,     0.1,     0.1,     0.1,     0.1]