/**:
  ros__parameters:

    chassis_mode: 0
    # 0->enable all, 1->only chassis movement, 2->only absolute movement, 3->only natural movement

    motor_count:  7
    motor_ids:    [1, 2, 3, 4, 5, 6, 7]
    motor_brands: [0, 0, 0, 0, 0, 0, 0] # 0->dji, 1->dm
    motor_modes:  [0, 0, 0, 0, 0, 0, 0] # 0->vel, 1->pos/mit, 2->pos_vel
    motor_types:  [0, 0, 0, 0, 0, 1, 1]
    # for dji: 0->3508, 1->6020
    # for dm: 0->4310

    p2v_kps: [0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     1.0]
    p2v_kis: [0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     1.0]
    p2v_kds: [0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     1.0]

    v2c_kps: [0.004,   0.004,   0.004,   0.004,   0.004,   0.004,   0.004]
    v2c_kis: [0.00003, 0.00003, 0.00003, 0.00003, 0.00003, 0.00003, 0.00003]
    v2c_kds: [0.1,     0.1,     0.1,     0.1,     0.1,     0.1,     0.1]