/**:
  ros__parameters:

    north_offset: 0.0 # rad,   north against the desired front
    auto_rotate: 7.0 # rad/s,   of the chassis
    comp_ratio: 0.80
    serial_path: "/dev/ttyUSB0"

    control:
      trans_vel: 3.0 # m/s
      rot_vel: 6.0 # rad/s
      aim_sensitivity: 3.14 # rad/s
      deadzone: 0.15 # percentage
    
    chassis:
      wheel_radius: 0.066 # 0.076 # m
      deceleration_ratio: 20.0
      chassis_radius: 0.255 # m
      yaw_offset: 0.0 # rad, yaw's zero against the chassis front

    gimbal:
      fric_vel_u: -800.0
      fric_vel_d: +800.0
      feed_vel_l: 15.0
      feed_vel_r: -15.0
      feed_ratio: 36.0
      fric_ratio: 1.0
      search_vel: 0.0
      feed_vib_freq: 2.0
      feed_vib_amp: 0.0
      pitch_freq: 2.0
      pitch_amp: 0.0

    motor:
      count:  10
      rids:   ["F",       "L",       "B",       "R",       "FRIC_U",  "FRIC_D",  "FEED_L",  "FEED_R",  "YAW",     "PITCH"]
      hids:   [1,         4,         2,         3,         5,         6,         7,         8,         5,         6]
      brands: [0,         0,         0,         0,         0,         0,         0,         0,         0,         0] # 0->dji,   1->dm
      types:  [0,         0,         0,         0,         0,         0,         2,         2,         1,         1]
      # for dji: 0->3508,   1->6020,   2->2006
      # for dm: 0->vel,   1->mit,   2->pos_vel
      p2v:
        kps:  [0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       2.0E+0,    1.3E+1] # 6, 
        kis:  [0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0E-1,    6.0E-1]
        kds:  [0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       0.0,       10.0E+5,    2.0E+6]
      v2c:
        kps:  [3.5E-3,    3.5E-3,    3.5E-3,    3.5E-3,    2.5E-3,    2.0E-3,    6.0E-3,    6.0E-3,    0.6E+0,    0.0E-1]
        kis:  [0.5E-5,    0.5E-5,    0.5E-5,    0.5E-5,    0.4E-4,    0.3E-4,    0.7E-3,    0.7E-3,    0.5E+0,    0.0E+0]
        kds:  [0.0E+3,    0.0E+3,    0.0E+3,    0.0E+3,    1.0E+3,    1.0E+3,    2.0E+2,    5.0E+2,    2.0E+4,    0.0E+2]

        # 1.0E-3