/**:
  ros__parameters:
    dbus_port: "dbus_serial"

    control:
      trans_vel: 2.5 # m/s
      rot_vel: 3.0 # rad/s
      stick_sens: 5.00 # rad/s
      mouse_sens: 10.0
      height_sens: 0.4 # m/s
      deadzone: 0.15 # percentage

    motor:
      count:  4
      rids:   ["L_LEG",   "R_LEG",   "R_WHL",   "L_WHL"]
      hids:   [2,         1,         1,         3]
      ports:  ["CAN0",    "CAN0",    "CAN0",    "CAN0"]
      brands: ["DM",      "DM",      "DJI",     "DJI"]
      types:  ["4310",    "4310",    "3508",    "3508"]

      p2v:
        kps:  [3.4E+1,    3.4E+1,    0.0,       0.0]
        kis:  [0.0,       0.0,       0.0,       0.0]
        kds:  [9.8E-1,    9.8E-1,    0.0,       0.0]
      v2t:
        kps:  [0.0,       0.0,       3.0E-2,    3.0E-2]
        kis:  [0.0,       0.0,       1.0E-2,    1.0E-2]
        kds:  [0.0,       0.0,       0.0,       0.0]

      cali:   [0,         0,         0,         0]