name: ROS2 Humble Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install curl
      run: sudo apt update && sudo apt install -y curl
    - name: Ignore scara_moveit
      run: touch decomposition/scara_moveit/AMENT_IGNORE
    - name: Setup ROS 2 Humble
      run: |
        rosdep update
        rosdep install -y --rosdistro humble --from-paths . --ignore-src
        colcon build --packages-skip-regex '.*'
    - name: Install ament_cmake_auto
      run: sudo apt install -y ros-humble-ament-cmake-auto
    - name: Build workspace
      uses: ichiro-its/ros2-ws-action/build@v1.0.1
