name: ROS2 Humble Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Ignore scara_moveit
      run: touch decomposition/scara_moveit/AMENT_IGNORE
    - name: ROS 2 Humble Env
      uses: ichiro-its/ros2-ci@v1.0.0
      with:
        ros2-distro: humble
        apt-packages: ros-humble-serial-driver ros-humble-camera-info-manager ros-humble-image-transport ros-humble-image-transport-plugins ros-humble-angles ros-humble-xacro ros-humble-cv-bridge
